package de.iothings.recrep.model;

/**
 * Created by johannes on 24.12.16.
 */
public enum RecrepEventType {

    RECORDSTREAM_CREATED,
    RECORDSTREAM_ENDED,
    REPLAYSTREAM_ENDPOINT_READY,
    REPLAYSTREAM_CREATED,
    REPLAYSTREAM_ENDED,
    RECORDJOB_REQUEST,
    RECORDJOB_CANCEL_REQUEST,
    RECORDJOB_STARTED,
    RECORDJOB_FINISHED,
    RECORDJOB_ANALYSIS_REQUEST,
    RECORDJOB_ANALYSIS_RESULT,
    REPLAYJOB_REQUEST,
    REPLAYJOB_CANCEL_REQUEST,
    REPLAYJOB_STARTED,
    REPLAYJOB_FINISHED,
    RECORDJOB_INVENTORY,
    CONFIGURATION_UPDATE

}
